# -*- coding: utf-8 -*-

{
    'name': "Website Help Desk / Support Ticket",
    'version': "1.5.15",
    'author': "Harshal Bhoir (WALPLAST)",
    'category': "Tools",
    'sequence': 1,
    'summary': "A helpdesk / support ticket system for your website",
    'description': "A helpdesk / support ticket system for your website",
    'license':'LGPL-3',
    'data': [
        'data/res.groups.csv',
        'security/website_support_security.xml',
        'security/ir.model.access.csv',

        'views/website_support_ticket_templates.xml',
        'views/website_support_ticket_compose_views.xml',
        'views/website_support_ticket_close_views.xml',
        'views/website_support_ticket_views.xml',
        'views/website_support_ticket_categories_views.xml',
        'views/website_support_ticket_subcategory_views.xml',
        'views/website_support_ticket_states_views.xml',
        'views/res_partner_views.xml',
        'views/budget_view.xml',
        'views/asset_maintenance_view.xml',
        'views/res_users_views.xml',
        'views/website_support_help_groups_views.xml',
        'views/website_support_help_page_views.xml',
        'views/website_support_ticket_priority_views.xml',
        'views/res_company_views.xml',
        'views/website_support_settings_views.xml',
        'views/website_support_ticket_department_views.xml',
        'data/website.support.ticket.states.xml',
        'data/website.support.ticket.categories.xml',
        'data/website.menu.csv',
        'data/website.support.ticket.priority.xml',
        'data/website.support.settings.xml',
        'data/website.support.department.role.csv',
        'data/account.analytic.account.csv',
        'data/mail_template.xml',
        'data/asset_sequence.xml',
        'views/hr_analytic_timesheet.xml',
        'views/hr_timesheet_sheet.xml',
        "views/project_view.xml",
        'report/report_timesheets.xml',
        'report/ticket_report_view.xml',
        'wizard/timesheet_wizard.xml',
        # 'wizard/bt_timesheet_analyis_report.xml',
        'views/asset_move_view.xml',
        'report/asset_details_report_view.xml',
        'report/asset_simple_report_view.xml',
        'report/payment_detail_report_view.xml',
        'views/payment_view.xml',
        'views/asset_allocation_view.xml',
        'views/asset_view.xml',
        'views/website_support_menus.xml',
    ],
    'demo': [],
    'depends': ['mail','purchase','web', 'crm', 'website','hr_timesheet_sheet','hr_timesheet','hr','project','web_timeline'],
    'images':[
        'static/description/3.jpg',
        'static/description/1.jpg',
        'static/description/2.jpg',
        'static/description/4.jpg',
        'static/description/5.jpg',
        'static/description/6.jpg',
    ],
    'installable': True,
    'application': True,
}